name: gorgona_new
channels:
  - https://conda.ovito.org
  - conda-forge
  - defaults
dependencies:
  - anari_ovito=0.8.1
  - anyio=4.4.0
  - aom=3.9.1
  - appnope=0.1.4
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=2.4.1
  - async-lru=2.0.4
  - attrs=23.2.0
  - aws-c-auth=0.7.22
  - aws-c-cal=0.6.14
  - aws-c-common=0.9.19
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.1
  - aws-c-io=0.14.8
  - aws-c-mqtt=0.10.4
  - aws-c-s3=0.5.9
  - aws-c-sdkutils=0.1.16
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.26.9
  - aws-sdk-cpp=1.11.329
  - azure-core-cpp=1.11.1
  - azure-identity-cpp=1.6.0
  - azure-storage-blobs-cpp=12.10.0
  - azure-storage-common-cpp=12.5.0
  - babel=2.14.0
  - beautifulsoup4=4.12.3
  - bleach=6.1.0
  - blosc=1.21.5
  - branca=0.7.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.28.1
  - ca-certificates=2024.6.2
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.0
  - certifi=2024.6.2
  - cffi=1.16.0
  - cfitsio=4.4.0
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.2.1
  - cycler=0.12.1
  - dav1d=1.2.1
  - debugpy=1.8.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - double-conversion=3.3.0
  - entrypoints=0.4
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.6.2
  - ffmpeg=6.1.1
  - fmt=10.2.1
  - folium=0.17.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.53.0
  - fqdn=1.5.1
  - freetype=2.12.1
  - freexl=2.0.0
  - fribidi=1.0.10
  - gdal=3.9.0
  - geojson=3.1.0
  - geopandas=1.0.0
  - geopandas-base=1.0.0
  - geos=3.12.1
  - geotiff=1.7.3
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - giflib=5.2.2
  - glib=2.80.2
  - glib-tools=2.80.2
  - gmp=6.3.0
  - gnutls=3.7.9
  - graphite2=1.3.13
  - gst-plugins-base=1.22.9
  - gstreamer=1.22.9
  - h11=0.14.0
  - h2=4.1.0
  - harfbuzz=8.5.0
  - hdf4=4.2.15
  - hdf5=1.14.3
  - hpack=4.0.0
  - httpcore=1.0.5
  - httpx=0.27.0
  - hyperframe=6.0.1
  - icu=73.2
  - idna=3.7
  - importlib-metadata=7.2.0
  - importlib_metadata=7.2.0
  - importlib_resources=6.4.0
  - ipykernel=6.29.4
  - ipython=8.25.0
  - ipywidgets=8.1.3
  - isoduration=20.11.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - json-c=0.17
  - json5=0.9.25
  - jsonpointer=3.0.0
  - jsonschema=4.22.0
  - jsonschema-specifications=2023.12.1
  - jsonschema-with-format-nongpl=4.22.0
  - jupyter=1.0.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.2
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.1
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.2.2
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.2
  - jupyterlab_widgets=3.0.11
  - kealib=1.5.3
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lame=3.100
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240116.2
  - libaec=1.1.3
  - libarchive=3.7.4
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libass=0.17.1
  - libblas=3.9.0
  - libboost-headers=1.85.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang=16.0.6
  - libclang-cpp16=16.0.6
  - libclang13=16.0.6
  - libcrc32c=1.1.2
  - libcurl=8.8.0
  - libcxx=17.0.6
  - libdeflate=1.20
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgdal=3.9.0
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libglib=2.80.2
  - libgoogle-cloud=2.24.0
  - libgoogle-cloud-storage=2.24.0
  - libgrpc=1.62.2
  - libhwloc=2.10.0
  - libiconv=1.17
  - libidn2=2.3.7
  - libintl=0.22.5
  - libintl-devel=0.22.5
  - libjpeg-turbo=3.0.0
  - libkml=1.3.0
  - liblapack=3.9.0
  - libllvm16=16.0.6
  - libnetcdf=4.9.2
  - libnghttp2=1.58.0
  - libogg=1.3.4
  - libopenblas=0.3.27
  - libopenvino=2024.1.0
  - libopenvino-arm-cpu-plugin=2024.1.0
  - libopenvino-auto-batch-plugin=2024.1.0
  - libopenvino-auto-plugin=2024.1.0
  - libopenvino-hetero-plugin=2024.1.0
  - libopenvino-ir-frontend=2024.1.0
  - libopenvino-onnx-frontend=2024.1.0
  - libopenvino-paddle-frontend=2024.1.0
  - libopenvino-pytorch-frontend=2024.1.0
  - libopenvino-tensorflow-frontend=2024.1.0
  - libopenvino-tensorflow-lite-frontend=2024.1.0
  - libopus=1.3.1
  - libpng=1.6.43
  - libpq=16.3
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libspatialite=5.1.0
  - libsqlite=3.46.0
  - libssh=0.10.6
  - libssh2=1.11.0
  - libtasn1=4.19.0
  - libtiff=4.6.0
  - libunistring=0.9.10
  - libvorbis=1.3.7
  - libvpx=1.14.1
  - libwebp-base=1.4.0
  - libxcb=1.15
  - libxml2=2.12.7
  - libxslt=1.1.39
  - libzip=1.10.1
  - libzlib=1.2.13
  - llvm-openmp=18.1.8
  - lz4-c=1.9.4
  - lzo=2.10
  - mapclassify=2.6.1
  - markupsafe=2.1.5
  - minizip=4.0.6
  - mistune=3.0.2
  - munkres=1.1.4
  - mysql-common=8.3.0
  - mysql-libs=8.3.0
  - nbclient=0.10.0
  - nbconvert=7.16.4
  - nbconvert-core=7.16.4
  - nbconvert-pandoc=7.16.4
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nettle=3.9.1
  - networkx=3.3
  - notebook=7.2.1
  - notebook-shim=0.2.4
  - nspr=4.35
  - nss=3.100
  - numpy=1.26.4
  - openh264=2.4.1
  - openjpeg=2.5.2
  - openssl=3.3.1
  - ospray_ovito=3.0.0
  - overrides=7.7.0
  - ovito=3.10.6
  - p11-kit=0.24.1
  - packaging=24.1
  - pandas=1.5.2
  - pandoc=3.2
  - pandocfilters=1.5.0
  - parso=0.8.4
  - patsy=0.5.6
  - pcre2=10.43
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.3.0
  - pip=24.0
  - pixman=0.43.4
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.2.2
  - poppler=24.04.0
  - poppler-data=0.4.12
  - postgresql=16.3
  - proj=9.4.0
  - prometheus_client=0.20.0
  - prompt-toolkit=3.0.47
  - prompt_toolkit=3.0.47
  - psutil=5.9.8
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pugixml=1.14
  - pure_eval=0.2.2
  - pycparser=2.22
  - pygments=2.18.0
  - pyobjc-core=10.3.1
  - pyobjc-framework-cocoa=10.3.1
  - pyogrio=0.8.0
  - pyparsing=3.1.2
  - pyproj=3.6.1
  - pyside6=6.6.2
  - pysocks=1.7.1
  - python=3.11.9
  - python-dateutil=2.9.0
  - python-fastjsonschema=2.20.0
  - python-json-logger=2.0.7
  - python_abi=3.11
  - pytz=2024.1
  - pyyaml=6.0.1
  - pyzmq=26.0.3
  - qt6-main=6.6.2
  - qtconsole-base=5.5.2
  - qtpy=2.4.1
  - re2=2023.09.01
  - readline=8.2
  - referencing=0.35.1
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.18.1
  - scikit-learn=1.5.0
  - scipy=1.12.0
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.3
  - setuptools=70.1.0
  - shapely=2.0.4
  - six=1.16.0
  - snappy=1.2.0
  - sniffio=1.3.1
  - soupsieve=2.5
  - spdlog=1.13.0
  - sqlite=3.46.0
  - stack_data=0.6.2
  - statsmodels=0.14.2
  - svt-av1=2.1.0
  - tbb=2021.12.0
  - terminado=0.18.1
  - threadpoolctl=3.5.0
  - tiledb=2.23.0
  - tinycss2=1.3.0
  - tk=8.6.13
  - tomli=2.0.1
  - tornado=6.4.1
  - tqdm=4.66.4
  - traitlets=5.14.3
  - traits=6.4.3
  - types-python-dateutil=2.9.0.20240316
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - tzcode=2024a
  - tzdata=2024a
  - uri-template=1.3.0
  - uriparser=0.9.8
  - urllib3=2.2.2
  - wcwidth=0.2.13
  - webcolors=24.6.0
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.43.0
  - widgetsnbextension=4.0.11
  - x264=1!164.3095
  - x265=3.5
  - xerces-c=3.2.5
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xyzservices=2024.6.0
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.19.2
  - zlib=1.2.13
  - zstd=1.5.6
prefix: /Users/nbykov/miniconda3/envs/gorgona_new
