name: gorgona_x
channels:
  - https://conda.ovito.org
  - conda-forge
  - defaults
dependencies:
  - python=3.11.9
  - numpy=1.26.4
  - pandas=1.5.2
  - scipy=1.12.0
  - matplotlib=3.8.2
  - seaborn=0.13.2
  - tqdm=4.66.4
  - jupyter=1.0.0
  - notebook=7.2.1
  - ovito=3.10.6
